USE housing_database;

-- 1. Insert Municipalities
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (1, '''s-Gravenhage');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (2, '''s-Hertogenbosch');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (3, 'Aa en Hunze');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (4, 'Aalten');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (5, 'Alkmaar');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (6, 'Almelo');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (7, 'Alphen-Chaam');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (8, 'Altena');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (9, 'Amstelveen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (10, 'Amsterdam');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (11, 'Apeldoorn');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (12, 'Arnhem');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (13, 'Assen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (14, 'Asten');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (15, 'Baarle-Nassau');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (16, 'Barneveld');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (17, 'Berg en Dal');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (18, 'Bergeijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (19, 'Bergen op Zoom');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (20, 'Berkelland');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (21, 'Bernheze');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (22, 'Best');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (23, 'Beuningen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (24, 'Bladel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (25, 'Boekel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (26, 'Borger-Odoorn');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (27, 'Borne');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (28, 'Boxtel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (29, 'Breda');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (30, 'Bronckhorst');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (31, 'Brummen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (32, 'Budel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (33, 'Buren');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (34, 'Coevorden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (35, 'Cranendonck');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (36, 'Culemborg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (37, 'Dalfsen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (38, 'De Wolden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (39, 'Deurne');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (40, 'Deventer');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (41, 'Dinkelland');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (42, 'Doesburg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (43, 'Doetinchem');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (44, 'Dongen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (45, 'Drimmelen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (46, 'Druten');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (47, 'Duiven');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (48, 'Echt');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (49, 'Ede');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (50, 'Eemsdelta');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (51, 'Eersel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (52, 'Eijsden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (53, 'Eindhoven');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (54, 'Elburg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (55, 'Emmen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (56, 'Enschede');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (57, 'Epe');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (58, 'Ermelo');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (59, 'Etten-Leur');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (60, 'Geertruidenberg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (61, 'Geldrop-Mierlo');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (62, 'Geleen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (63, 'Gemert-Bakel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (64, 'Gilze en Rijen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (65, 'Goirle');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (66, 'Groningen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (67, 'Haaksbergen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (68, 'Haarlem');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (69, 'Halderberge');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (70, 'Hardenberg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (71, 'Harderwijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (72, 'Hattem');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (73, 'Heerde');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (74, 'Heerlen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (75, 'Heeze-Leende');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (76, 'Hellendoorn');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (77, 'Helmond');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (78, 'Hengelo');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (79, 'Het Hogeland');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (80, 'Heumen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (81, 'Heusden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (82, 'Hilvarenbeek');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (83, 'Hof van Twente');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (84, 'Hoogeveen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (85, 'Kampen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (86, 'Kerkrade');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (87, 'Laarbeek');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (88, 'Land van Cuijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (89, 'Landgraaf');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (90, 'Leeuwarden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (91, 'Lelystad');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (92, 'Lingewaard');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (93, 'Lochem');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (94, 'Loon op Zand');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (95, 'Losser');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (96, 'Maarheeze');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (97, 'Maasbracht');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (98, 'Maasdriel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (99, 'Maashorst');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (100, 'Maastricht');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (101, 'Meerssen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (102, 'Meierijstad');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (103, 'Meppel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (104, 'Middelburg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (105, 'Midden-Drenthe');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (106, 'Midden-Groningen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (107, 'Moerdijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (108, 'Montferland');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (109, 'Neder-Betuwe');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (110, 'Nijkerk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (111, 'Nijmegen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (112, 'Noordenveld');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (113, 'Nuenen, Gerwen en Nederwetten');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (114, 'Nunspeet');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (115, 'Oirschot');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (116, 'Oisterwijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (117, 'Oldambt');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (118, 'Oldebroek');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (119, 'Oldenzaal');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (120, 'Olst-Wijhe');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (121, 'Ommen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (122, 'Oost Gelre');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (123, 'Oosterhout');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (124, 'Oss');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (125, 'Oude IJsselstreek');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (126, 'Overbetuwe');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (127, 'Peel en Maas');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (128, 'Pekela');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (129, 'Putten');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (130, 'Raalte');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (131, 'Renkum');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (132, 'Reusel-De Mierden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (133, 'Rheden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (134, 'Rijssen-Holten');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (135, 'Roermond');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (136, 'Roosendaal');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (137, 'Rucphen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (138, 'Scherpenzeel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (139, 'Simpelveld');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (140, 'Sint-Michielsgestel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (141, 'Sittard');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (142, 'Sittard-Geleen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (143, 'Someren');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (144, 'Son en Breugel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (145, 'Stadskanaal');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (146, 'Staphorst');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (147, 'Steenbergen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (148, 'Steenwijkerland');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (149, 'Tiel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (150, 'Tilburg');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (151, 'Tubbergen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (152, 'Twenterand');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (153, 'Tynaarlo');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (154, 'Utrecht');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (155, 'Valkenswaard');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (156, 'Veendam');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (157, 'Veldhoven');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (158, 'Voorst');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (159, 'Vught');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (160, 'Waalre');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (161, 'Waalwijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (162, 'Wageningen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (163, 'Weert');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (164, 'West Betuwe');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (165, 'West Maas en Waal');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (166, 'Westerkwartier');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (167, 'Westerveld');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (168, 'Westervoort');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (169, 'Westerwolde');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (170, 'Wierden');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (171, 'Wijchen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (172, 'Winterswijk');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (173, 'Woensdrecht');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (174, 'Zaltbommel');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (175, 'Zevenaar');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (176, 'Zundert');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (177, 'Zutphen');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (178, 'Zwartewaterland');
INSERT INTO Municipality (municipality_id, municipality_name) VALUES (179, 'Zwolle');

-- 2. Insert Housing Types (Static)
INSERT INTO Housing_Type (housing_type_id, housing_type_name) VALUES (1, 'Bestaande koopwoningen');

-- 3. Insert Household Types (Static)
INSERT INTO Household_Type (household_type_id, household_type_name) VALUES (1, 'Particuliere huishoudens');

-- 4. Insert Housing Statistics
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (1, 1995, 84638.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (2, 1995, 110371.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (3, 1995, 98008.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (4, 1995, 80240.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (5, 1995, 75013.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (6, 1995, 118689.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (7, 1995, 84558.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (8, 1995, 100616.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (9, 1995, 99267.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (10, 1995, 96700.0, 32, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (11, 1995, 91650.0, 48, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (12, 1995, 108135.0, 52, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (13, 1995, 87095.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (14, 1995, 85034.0, 62, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (15, 1995, 74053.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (16, 1995, 62635.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (17, 1995, 83039.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (18, 1995, 79269.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (19, 1995, 81706.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (20, 1995, 100092.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (21, 1995, 85999.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (22, 1995, 89040.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (23, 1995, 56599.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (24, 1995, 80373.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (25, 1995, 125074.0, 96, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (26, 1995, 93852.0, 97, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (27, 1995, 96899.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (28, 1995, 121818.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (29, 1995, 88136.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (30, 1995, 85792.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (31, 1995, 101064.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (32, 1995, 95212.0, 141, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (33, 1995, 78212.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (34, 1995, 85568.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (35, 1995, 94637.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (36, 1995, 97123.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (37, 1995, 96925.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (38, 1995, 84813.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (39, 2000, 141369.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (40, 2000, 244012.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (41, 2000, 224938.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (42, 2000, 149386.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (43, 2000, 120177.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (44, 2000, 205439.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (45, 2000, 139511.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (46, 2000, 199043.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (47, 2000, 166012.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (48, 2000, 145973.0, 48, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (49, 2000, 216969.0, 52, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (50, 2000, 178190.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (51, 2000, 144264.0, 62, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (52, 2000, 135368.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (53, 2000, 99943.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (54, 2000, 163672.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (55, 2000, 125627.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (56, 2000, 178004.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (57, 2000, 191688.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (58, 2000, 129601.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (59, 2000, 144064.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (60, 2000, 95702.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (61, 2000, 131274.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (62, 2000, 165942.0, 97, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (63, 2000, 162594.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (64, 2000, 189982.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (65, 2000, 123880.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (66, 2000, 144971.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (67, 2000, 151019.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (68, 2000, 162963.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (69, 2000, 171128.0, 141, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (70, 2000, 154308.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (71, 2000, 165717.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (72, 2000, 200793.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (73, 2000, 181779.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (74, 2000, 182852.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (75, 2000, 155551.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (76, 2005, 190238.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (77, 2005, 286003.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (78, 2005, 238189.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (79, 2005, 188779.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (80, 2005, 168939.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (81, 2005, 299513.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (82, 2005, 212656.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (83, 2005, 272690.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (84, 2005, 232403.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (85, 2005, 255386.0, 52, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (86, 2005, 211986.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (87, 2005, 195514.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (88, 2005, 164280.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (89, 2005, 227984.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (90, 2005, 142184.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (91, 2005, 230095.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (92, 2005, 246806.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (93, 2005, 131913.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (94, 2005, 164228.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (95, 2005, 143596.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (96, 2005, 174333.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (97, 2005, 203057.0, 97, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (98, 2005, 210951.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (99, 2005, 257599.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (100, 2005, 214129.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (101, 2005, 192044.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (102, 2005, 217413.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (103, 2005, 190564.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (104, 2005, 179674.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (105, 2005, 207675.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (106, 2005, 219305.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (107, 2005, 240032.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (108, 2005, 246223.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (109, 2005, 221940.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (110, 2005, 206170.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (111, 2010, 211926.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (112, 2010, 312791.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (113, 2010, 281206.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (114, 2010, 204498.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (115, 2010, 186206.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (116, 2010, 268023.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (117, 2010, 222397.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (118, 2010, 285257.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (119, 2010, 268988.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (120, 2010, 284009.0, 52, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (121, 2010, 218423.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (122, 2010, 227616.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (123, 2010, 180217.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (124, 2010, 267413.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (125, 2010, 143523.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (126, 2010, 232173.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (127, 2010, 261128.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (128, 2010, 146410.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (129, 2010, 174867.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (130, 2010, 162912.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (131, 2010, 193575.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (132, 2010, 222775.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (133, 2010, 249708.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (134, 2010, 206310.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (135, 2010, 219800.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (136, 2010, 200608.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (137, 2010, 213695.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (138, 2010, 175806.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (139, 2010, 176320.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (140, 2010, 216804.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (141, 2010, 252064.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (142, 2010, 259586.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (143, 2010, 247848.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (144, 2010, 217371.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (145, 2010, 223622.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (146, 2015, 194809.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (147, 2015, 331763.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (148, 2015, 303925.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (149, 2015, 199528.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (150, 2015, 183838.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (151, 2015, 254242.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (152, 2015, 207778.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (153, 2015, 246872.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (154, 2015, 246592.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (155, 2015, 212919.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (156, 2015, 231302.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (157, 2015, 177441.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (158, 2015, 268197.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (159, 2015, 144517.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (160, 2015, 213328.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (161, 2015, 253262.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (162, 2015, 143898.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (163, 2015, 166851.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (164, 2015, 157690.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (165, 2015, 179997.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (166, 2015, 221578.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (167, 2015, 223017.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (168, 2015, 193782.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (169, 2015, 213872.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (170, 2015, 194640.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (171, 2015, 200959.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (172, 2015, 162787.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (173, 2015, 174285.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (174, 2015, 204190.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (175, 2015, 245900.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (176, 2015, 259935.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (177, 2015, 233399.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (178, 2015, 217850.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (179, 2015, 218349.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (180, 2020, 313937.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (181, 2020, 534717.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (182, 2020, 510919.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (183, 2020, 279571.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (184, 2020, 250572.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (185, 2020, 314453.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (186, 2020, 278752.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (187, 2020, 318532.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (188, 2020, 378935.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (189, 2020, 344024.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (190, 2020, 355807.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (191, 2020, 278720.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (192, 2020, 447447.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (193, 2020, 202356.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (194, 2020, 305792.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (195, 2020, 371124.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (196, 2020, 194105.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (197, 2020, 217604.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (198, 2020, 230738.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (199, 2020, 273122.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (200, 2020, 316733.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (201, 2020, 313281.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (202, 2020, 271151.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (203, 2020, 295228.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (204, 2020, 268453.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (205, 2020, 283960.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (206, 2020, 221359.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (207, 2020, 227165.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (208, 2020, 293733.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (209, 2020, 405791.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (210, 2020, 384498.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (211, 2020, 324796.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (212, 2020, 286721.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (213, 2020, 315874.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (214, 2021, 365446.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (215, 2021, 625658.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (216, 2021, 569890.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (217, 2021, 344738.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (218, 2021, 301082.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (219, 2021, 366251.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (220, 2021, 307371.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (221, 2021, 404430.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (222, 2021, 427348.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (223, 2021, 367046.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (224, 2021, 411717.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (225, 2021, 321804.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (226, 2021, 507862.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (227, 2021, 230616.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (228, 2021, 339835.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (229, 2021, 412222.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (230, 2021, 216618.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (231, 2021, 257710.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (232, 2021, 262188.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (233, 2021, 332187.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (234, 2021, 353620.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (235, 2021, 355909.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (236, 2021, 321374.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (237, 2021, 325223.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (238, 2021, 318961.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (239, 2021, 315735.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (240, 2021, 288495.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (241, 2021, 266384.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (242, 2021, 342612.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (243, 2021, 469949.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (244, 2021, 435660.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (245, 2021, 364015.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (246, 2021, 330617.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (247, 2021, 363081.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (248, 2022, 399298.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (249, 2022, 658372.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (250, 2022, 620954.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (251, 2022, 383699.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (252, 2022, 330027.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (253, 2022, 426396.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (254, 2022, 321657.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (255, 2022, 466586.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (256, 2022, 470555.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (257, 2022, 411914.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (258, 2022, 454312.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (259, 2022, 353917.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (260, 2022, 561362.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (261, 2022, 251269.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (262, 2022, 382110.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (263, 2022, 463836.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (264, 2022, 237848.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (265, 2022, 282061.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (266, 2022, 287719.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (267, 2022, 380395.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (268, 2022, 369617.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (269, 2022, 373464.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (270, 2022, 336663.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (271, 2022, 376418.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (272, 2022, 358354.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (273, 2022, 343792.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (274, 2022, 296350.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (275, 2022, 292836.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (276, 2022, 384896.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (277, 2022, 510980.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (278, 2022, 499968.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (279, 2022, 396309.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (280, 2022, 370896.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (281, 2022, 414535.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (282, 2023, 393418.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (283, 2023, 615382.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (284, 2023, 568161.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (285, 2023, 369114.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (286, 2023, 334100.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (287, 2023, 391221.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (288, 2023, 338389.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (289, 2023, 445741.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (290, 2023, 437260.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (291, 2023, 404275.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (292, 2023, 413689.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (293, 2023, 349931.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (294, 2023, 507289.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (295, 2023, 246595.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (296, 2023, 389050.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (297, 2023, 443955.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (298, 2023, 242591.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (299, 2023, 271284.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (300, 2023, 294731.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (301, 2023, 372216.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (302, 2023, 374547.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (303, 2023, 368487.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (304, 2023, 345346.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (305, 2023, 371634.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (306, 2023, 344337.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (307, 2023, 342488.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (308, 2023, 305913.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (309, 2023, 299110.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (310, 2023, 371491.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (311, 2023, 474406.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (312, 2023, 486364.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (313, 2023, 394820.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (314, 2023, 354656.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (315, 2023, 410024.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (316, 2024, 381336.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (317, 2024, 649823.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (318, 2024, 617647.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (319, 2024, 403201.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (320, 2024, 361465.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (321, 2024, 417733.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (322, 2024, 360624.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (323, 2024, 468999.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (324, 2024, 484925.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (325, 2024, 450380.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (326, 2024, 447417.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (327, 2024, 373411.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (328, 2024, 548843.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (329, 2024, 270045.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (330, 2024, 434832.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (331, 2024, 478097.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (332, 2024, 262548.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (333, 2024, 291195.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (334, 2024, 310226.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (335, 2024, 405965.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (336, 2024, 394938.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (337, 2024, 392004.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (338, 2024, 376819.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (339, 2024, 419759.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (340, 2024, 377867.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (341, 2024, 364655.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (342, 2024, 348742.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (343, 2024, 314825.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (344, 2024, 398630.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (345, 2024, 519924.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (346, 2024, 512413.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (347, 2024, 417622.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (348, 2024, 391906.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (349, 2024, 450763.0, 179, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (350, 2025, 424065.0, 5, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (351, 2025, 681691.0, 9, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (352, 2025, 630621.0, 10, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (353, 2025, 407247.0, 12, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (354, 2025, 376755.0, 13, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (355, 2025, 465201.0, 15, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (356, 2025, 398490.0, 19, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (357, 2025, 522253.0, 28, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (358, 2025, 509387.0, 29, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (359, 2025, 469870.0, 53, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (360, 2025, 465418.0, 1, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (361, 2025, 396626.0, 66, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (362, 2025, 576569.0, 68, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (363, 2025, 284279.0, 74, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (364, 2025, 458882.0, 77, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (365, 2025, 506467.0, 2, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (366, 2025, 270119.0, 86, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (367, 2025, 327701.0, 89, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (368, 2025, 319443.0, 90, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (369, 2025, 426903.0, 91, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (370, 2025, 413671.0, 100, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (371, 2025, 473060.0, 101, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (372, 2025, 393274.0, 104, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (373, 2025, 449898.0, 127, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (374, 2025, 373963.0, 135, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (375, 2025, 389117.0, 136, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (376, 2025, 343886.0, 139, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (377, 2025, 338452.0, 142, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (378, 2025, 424838.0, 150, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (379, 2025, 549113.0, 154, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (380, 2025, 538756.0, 157, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (381, 2025, 453184.0, 161, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (382, 2025, 437149.0, 163, 1);
INSERT INTO Housing_Statistic (housing_statistic_id, year, average_sale_price, municipality_id, housing_type_id) VALUES (383, 2025, 450913.0, 179, 1);

-- 5. Insert Affordability Statistics
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (1, 2023, 56900.00, 3, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (2, 2023, 54600.00, 4, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (3, 2023, 49100.00, 6, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (4, 2023, 65600.00, 7, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (5, 2023, 61400.00, 8, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (6, 2023, 53200.00, 10, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (7, 2023, 54800.00, 11, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (8, 2023, 47000.00, 12, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (9, 2023, 49700.00, 13, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (10, 2023, 58400.00, 14, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (11, 2023, 56500.00, 15, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (12, 2023, 63300.00, 16, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (13, 2023, 54700.00, 17, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (14, 2023, 63900.00, 18, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (15, 2023, 53300.00, 19, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (16, 2023, 55500.00, 20, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (17, 2023, 63100.00, 21, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (18, 2023, 62200.00, 22, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (19, 2023, 59700.00, 23, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (20, 2023, 61600.00, 24, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (21, 2023, 62000.00, 25, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (22, 2023, 54100.00, 26, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (23, 2023, 59700.00, 27, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (24, 2023, 57500.00, 28, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (25, 2023, 55600.00, 29, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (26, 2023, 61900.00, 30, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (27, 2023, 57200.00, 31, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (28, 2023, 63600.00, 33, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (29, 2023, 53300.00, 34, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (30, 2023, 57700.00, 35, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (31, 2023, 57900.00, 36, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (32, 2023, 60400.00, 37, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (33, 2023, 56500.00, 39, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (34, 2023, 51400.00, 40, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (35, 2023, 63900.00, 41, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (36, 2023, 49100.00, 42, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (37, 2023, 53700.00, 43, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (38, 2023, 57400.00, 44, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (39, 2023, 60400.00, 45, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (40, 2023, 57500.00, 46, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (41, 2023, 60100.00, 47, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (42, 2023, 58600.00, 49, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (43, 2023, 46900.00, 50, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (44, 2023, 65900.00, 51, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (45, 2023, 49500.00, 53, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (46, 2023, 57700.00, 54, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (47, 2023, 48900.00, 55, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (48, 2023, 44400.00, 56, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (49, 2023, 60000.00, 57, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (50, 2023, 60000.00, 58, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (51, 2023, 56400.00, 59, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (52, 2023, 56400.00, 60, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (53, 2023, 57200.00, 61, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (54, 2023, 57400.00, 63, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (55, 2023, 56700.00, 64, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (56, 2023, 60100.00, 65, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (57, 2023, 40800.00, 66, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (58, 2023, 58000.00, 67, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (59, 2023, 56600.00, 69, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (60, 2023, 56400.00, 70, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (61, 2023, 57100.00, 71, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (62, 2023, 57500.00, 72, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (63, 2023, 58800.00, 73, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (64, 2023, 67100.00, 75, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (65, 2023, 57700.00, 76, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (66, 2023, 52700.00, 77, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (67, 2023, 50300.00, 78, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (68, 2023, 56400.00, 2, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (69, 2023, 62500.00, 80, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (70, 2023, 60800.00, 81, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (71, 2023, 64100.00, 82, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (72, 2023, 58700.00, 83, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (73, 2023, 50000.00, 79, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (74, 2023, 50300.00, 84, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (75, 2023, 54900.00, 85, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (76, 2023, 61100.00, 87, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (77, 2023, 58200.00, 88, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (78, 2023, 58800.00, 92, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (79, 2023, 63700.00, 93, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (80, 2023, 60500.00, 94, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (81, 2023, 57600.00, 95, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (82, 2023, 60200.00, 98, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (83, 2023, 58200.00, 99, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (84, 2023, 59700.00, 102, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (85, 2023, 52700.00, 103, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (86, 2023, 55300.00, 105, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (87, 2023, 48500.00, 106, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (88, 2023, 58200.00, 107, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (89, 2023, 55400.00, 108, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (90, 2023, 60200.00, 109, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (91, 2023, 64000.00, 110, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (92, 2023, 44400.00, 111, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (93, 2023, 55700.00, 112, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (94, 2023, 66800.00, 113, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (95, 2023, 58900.00, 114, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (96, 2023, 64200.00, 115, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (97, 2023, 66500.00, 116, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (98, 2023, 46600.00, 117, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (99, 2023, 58400.00, 118, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (100, 2023, 54800.00, 119, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (101, 2023, 58200.00, 120, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (102, 2023, 58000.00, 121, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (103, 2023, 58800.00, 122, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (104, 2023, 56500.00, 123, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (105, 2023, 55600.00, 124, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (106, 2023, 53200.00, 125, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (107, 2023, 60600.00, 126, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (108, 2023, 46000.00, 128, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (109, 2023, 62400.00, 129, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (110, 2023, 57400.00, 130, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (111, 2023, 59800.00, 131, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (112, 2023, 59200.00, 132, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (113, 2023, 52200.00, 133, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (114, 2023, 65700.00, 134, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (115, 2023, 52300.00, 136, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (116, 2023, 55900.00, 137, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (117, 2023, 61900.00, 138, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (118, 2023, 65700.00, 140, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (119, 2023, 61900.00, 143, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (120, 2023, 66400.00, 144, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (121, 2023, 47000.00, 145, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (122, 2023, 62200.00, 146, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (123, 2023, 54800.00, 147, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (124, 2023, 53300.00, 148, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (125, 2023, 51900.00, 149, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (126, 2023, 47600.00, 150, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (127, 2023, 64700.00, 151, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (128, 2023, 55800.00, 152, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (129, 2023, 62400.00, 153, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (130, 2023, 52200.00, 154, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (131, 2023, 55400.00, 155, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (132, 2023, 48300.00, 156, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (133, 2023, 60800.00, 157, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (134, 2023, 60600.00, 158, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (135, 2023, 70000.00, 159, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (136, 2023, 71400.00, 160, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (137, 2023, 53400.00, 161, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (138, 2023, 41100.00, 162, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (139, 2023, 64300.00, 164, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (140, 2023, 57900.00, 165, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (141, 2023, 56100.00, 166, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (142, 2023, 57700.00, 167, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (143, 2023, 51900.00, 168, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (144, 2023, 49100.00, 169, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (145, 2023, 67800.00, 170, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (146, 2023, 57800.00, 171, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (147, 2023, 53500.00, 172, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (148, 2023, 55600.00, 173, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (149, 2023, 61300.00, 38, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (150, 2023, 61100.00, 174, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (151, 2023, 52300.00, 175, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (152, 2023, 58800.00, 176, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (153, 2023, 50400.00, 177, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (154, 2023, 64700.00, 178, 1);
INSERT INTO Affordability_Statistic (affordability_statistic_id, year, average_income, municipality_id, household_type_id) VALUES (155, 2023, 52600.00, 179, 1);
